baseURL: "https://psira.me/"
languageCode: "en-us"
title: "Psira - Sira Pornsiriprasert"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination.pagerSize: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - identifier: projects
    #   name: Projects
    #   title: Projects
    #   url: /projects
    #   weight: 1
    # - identifier: research
    #   name: Research
    #   title: Research
    #   url: /research
    #   weight: 1
    - identifier: code
      name: Code
      title: Code
      url: /code
      weight: 3
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 3
    - identifier: about
      name: About Me
      title: About Me
      url: /#about
      weight: 4
    - identifier: contact
      name: Contact
      title: Contact
      url: /#contact
      weight: 5
      #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Psira"
  description: Personal website of Sira Pornsiriprasert, an MD-MEng student
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo/logo-universal.svg"
  socialPreview: "/images/white-coat-social-preview.jpg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "auto" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # Based on Catpuccin Latte
  color:
    textColor: "#292c3c"
    secondaryTextColor: "#4c4f69"
    textLinkColor: "#e64553" # Catpuccin Latte Maroon
    backgroundColor: "#eaedf0"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#000000"
    secondaryColor: "#f8f9fa"

    # Based on Catpuccin Frappe
    darkmode:
      textColor: "#EAECF2FF"
      secondaryTextColor: "#e7ebf0ff"
      textLinkColor: "#e64553" # Catpuccin Latte Maroon
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#ffffff"
      secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo/logo.svg" # Logo for the brand | default is the favicon variable
    brandLogoLight: "/logo/logo-light.svg"
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "sira" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  # Hero
  hero:
    enable: true
    intro: "MD-MEng Student"
    title: "Sira Pornsiriprasert"
    subtitle: "Psira"
    content: "I am a medical and master of engineering student, who likes to sing, code, and explore the world scientifically and philosophically."
    image: "/images/white-coat.jpg"
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Music (YT)"
      url: "https://www.youtube.com/@psira_music"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-instagram
          url: https://www.instagram.com/_psira_/
        - icon: fab fa-github
          url: https://github.com/p-sira

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/suit.jpg"
    content: |-
      I am a medical student at the Faculty of Medicine, Ramathibodi Hospital, Thailand,
      Currently, a member of the Center for Biomedical and Robotics Technology
      at Mahidol University, I am pursuing a master degree in Biomedical Engineering.

      I am naturally curious and constantly broadening my horizon. Among various
      interests, I enjoy learning languages, exploring the world, and meeting people
      across diverse culture. I strongly believe in and advocate for education rights.
      One of my life goals is to make education accessible and fair for everyone.

      Talk to me in: 🇬🇧 🇹🇭 🇨🇳 🇫🇷
    skills:
      enable: true
      title: "See my:"
      items:
        # - "[Projects](/projects)"
        # - "[Research](/research)"
        - "[Code](/code)"
        # - "[Gallery](/gallery)"
        - "[Experience](/#experience)"
        - "[Contact](/contact)"

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Doctor of Medicine"
        school:
          name: "Ramathibodi Hospital, Mahidol University, Thailand"
          url: "https://www.rama.mahidol.ac.th/en"
        date: "2021 - Ongoing"
        content: |-
          - Best Academic Performance Award
          - [Dean's Research Award](https://www.rama.mahidol.ac.th/nurturing_talent/th/tonkla/Sira)
          - Best Epidemiology Presentation 2022
      - title: "Master of Biomedical Engineering"
        school:
          name: "Mahidol University, Thailand"
          url: "https://www.eg.mahidol.ac.th/egmu_eng/"
        date: "2024 - Ongoing"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

  # projects
  projects:
    enable: false

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Head of RAMA Open House 2022 and Co-Head of RAMA Open House 2021"
        company: "RAMA Open House"
        companyUrl: "https://www.facebook.com/RAMAbyD/videos/rama-open-house-2022/1178326516112329/"
        date: "2022 and 2021"
        featuredLink:
          enable: false
          # name: "RAMA OPH 2022"
          # url: "https://www.facebook.com/RAMAbyD/videos/rama-open-house-2022/1178326516112329/"
        content: |
          The RAMA Open House was a large-scale event. After serving as the co-head in 2021, I reflected on the challenges and areas for improvement. These insights and experience were applied when I led the RAMA Open House 2022, resulting in more efficient management and stronger team coordination.
          - The team structure consisted of 6 teams: Activity, Human Resources and Registration, Document, Art, Technology and Production, and Public Relations teams, totaling over 200 members from multiple class years. Furthermore, the team collaborated with various departments, student clubs, and administrative staff.
          - The key aspects I was responsible for were team coordination, event planning, communication with the public and stakeholders, budgeting, logistics, and problem-solving. The RAMA Open House 2022 was the first on-site event after several years of pause. The COVID-19 pandemic introduced additional complexities to ensure rigorous health protocols.
          - During RAMA Open House 2022, all 700 available tickets were sold out within one minute. The event received positive feedback and valuable learning points from the participants and staff.
      - job: "BMAT Physics and Problem Solving Educator"
        company: "RAdiator"
        companyUrl: https://www.youtube.com/@radiator5264
        date: "May - August 2021"
        featuredLink:
          enable: false
        content: |
          <a href="https://www.youtube.com/watch?v=NhHpJJA9EfM&list=PLQskSFI79tG7-CPLJlzhSxZMjz26Kijm2&index=2" target="_blank">BMAT Physics</a> | <a href="https://www.youtube.com/watch?v=kPQHRUsnPC8&list=PLQskSFI79tG67KYfAesRPppvGWhX3zm2Q" target="_blank">BMAT Problem Solving</a> 
          
          The RAdiator is an educational platform targeting Thai high school students. We aim to provide free educational resources for university admission preparation. The RAdiator is a collaboration project by the first-year medical students at the Faculty of Medicine, Ramathibodi Hospital.
          - I worked on the Problem Solving part of the BMAT Section 1 and Physics of Section 2. In addition to teaching, I arranged the material and analyzed past papers to create custom practice problems to reinforce learning. 
          - The core principle I used was making challenging concepts more accessible through clear and intuitive explanations.
          - In total, I produced 10 videos, adding up to about 7 hours, receiving over 30,000 views.
      - job: "Open Source Project Contributor"
        company: "Open Source"
        companyUrl: https://www.psira.me/code
        date: "Since 2021"
        featuredLink:
          enable: true
          name: "See more"
          url: https://www.psira.me/code
        content: |
          Since I was young, I have always dreamed of writing my own libraries. Today, I am an active contributor to open source projects. I believe that strong community leads to robust and impactful code.
          - I like optimizing existing ideas and tackling unsolved problems with elegant solutions. I gravitate toward more fundamental libraries that serve as building blocks for scientific research. 
          - My interests are algorithms, science, medical applications, and cryptography. Recently, I took interest in agentic AI. I am open to exploring new fields to enhance multidisciplinary approaches.
          - I code in several languages, but I am most proficient in Python and Rust.
          <i class="fab fa-python" title="Python"></i>
          <i class="fab fa-rust" title="Rust"></i>
          C++
          C
          <iconify-icon icon="file-icons:matlab" title="MATLAB"></iconify-icon>
          <i class="fab fa-golang" title="GoLang"></i>
          <i class="fa fa-terminal" title="bash"></i>
          C#
          <i class="fab fa-html5" title="HTML+CSS"></i>
          <iconify-icon icon="devicon-plain:hugo" title="Hugo"></iconify-icon>
          <i class="fab fa-java" title="Java"></i>
          <iconify-icon icon="file-icons:arduino" title="Arduino and ESP-IDF"></iconify-icon>
          <iconify-icon icon="file-icons:wolfram" title="Wolfram"></iconify-icon>
          - I used to do Minecraft command blocks and redstone if you would count.

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: "Scientific and Mathematical Literacy 2020: Gold Medal"
        content: "Awarded by the IPST"
        url: https://www.ipst.ac.th/ipsten
      - title: "Thailand Geography Olympiad 2020: Gold Medal"
        content: "Awarded by the POSN"
        url: https://www.posn.or.th/
      - title: "Thailand Physics Olympiad 2020: Declaration of Honor"
        content: "Awarded by the POSN"
        url: https://www.posn.or.th/
      # - title: Hugo Profile
      # content: Developed a theme and getting 1K+ downloads per month.
      # url: "https://github.com/gurusabarish/hugo-profile"
      # image: /images/achievment.jpg

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: |-
      General: [contact@psira.me](mailto:contact@psira.me) &nbsp; | &nbsp; Code: [code@psira.me](mailto:code@psira.me) &nbsp; | &nbsp; Research: [research@psira.me](mailto:research@psira.me)

      I do not accept sponsors related to medical or health products.
    # btnName: Mail me
    # btnLink: mailto:
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      # youtube: https://github.com/p-sira
      # instagram: https://www.instagram.com/_psira_/
      # github: https://github.com/p-sira
      # linkedin: https://linkedin.com
      # twitter: https://twitter.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: false
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
