baseURL: "https://psira.me/"
languageCode: "en-us"
title: "Psira"
description: "Personal website of Sira Pornsiriprasert (สิร พรศิริประเสริฐ)"

params:
  dateFormat: "January 2, 2006"
  author: "Sira Pornsiriprasert"
  sitename: "Sira Pornsiriprasert - Psira"
  description: "Sira Pornsiriprasert (สิร พรศิริประเสริฐ) is a medical student at Ramathibodi Hospital and a Master of Biomedical Engineering candidate at Mahidol University, Thailand."

build:
  buildStats:
    enable: true
  cachebusters:
  - source: 'assets/notwatching/hugo_stats\.json'
    target: css
  - source: '(postcss|tailwind)\.config\.js'
    target: css
  - source: 'assets/css/.*\.css'
    target: css
module:
  mounts:
  - source: assets
    target: assets
  - disableWatch: true
    source: hugo_stats.json
    target: assets/notwatching/hugo_stats.json

ignoreFiles:
  - "data/fetcher/*"
  - "data/precompile/*"
